[database]
host = 127.0.0.1
port = 5432
database = json_parser
user = jarvis
password = psql
sslmode = prefer

[migration]
path = internal/db/migrations
# Migration SQL files are made and read from this folder